import type { Artist } from "@/lib/types";

export const artists: Artist[] = [
  {
    slug: "big-russ",
    name: "Big Russ",
    role: "Owner / Artist",
    bio: "Custom work with a focus on strong composition and clean execution. Bring your idea—APP will help shape it into a piece you'll wear forever.",
    avatarUrl: "/artists/big-russ.jpg",
    specialties: ["black_and_grey", "traditional", "custom"],
    facebookUrl: "https://www.facebook.com/addictivepain/",
    instagramUrl: "https://www.instagram.com/bigrussg518",
  },
  {
    slug: "kenny-briggs",
    name: "Kenny Briggs",
    role: "Artist",
    bio: "Bold lines, clean color, and classic foundations. Great for custom ideas that still read strong from a distance.",
    avatarUrl: "/artists/kenny-briggs.jpg",
    specialties: ["neo_traditional", "floral", "stipple"],
    facebookUrl: "https://www.facebook.com/addictivepain/",
    instagramUrl: "https://www.instagram.com/turkeytattoos",
  },
  {
    slug: "kade-zapp",
    name: "Kade Zapp",
    role: "Artist",
    bio: "Fine line and detailed black & grey—precision-focused with an emphasis on readability and placement.",
    avatarUrl: "/artists/kade-zapp.jpg",
    specialties: ["fine_line", "black_and_grey", "custom"],
    facebookUrl: "https://www.facebook.com/addictivepain/",
    instagramUrl: "https://www.instagram.com/",
  },
  {
    slug: "chris-cross",
    name: "Chris Cross",
    role: "Artist",
    bio: "Add a short bio for Chris Cross here—style, strengths, and what clients can expect.",
    avatarUrl: "/artists/chris-cross.jpg",
    specialties: ["anime", "neo_traditional", "traditional", "black_and_grey"],
    facebookUrl: "https://www.facebook.com/chrisx.cross.9",
    instagramUrl: "https://www.instagram.com/inkd_by_cross",
  },
  {
    slug: "marissa-millington",
    name: "Marisa K Millington",
    role: "Artist",
    bio: "Add a short bio for Marisa K Millington here—style, strengths, and what clients can expect.",
    avatarUrl: "/artists/marisa-millington.jpg",
    specialties: ["custom", "fine_line", "color"],
    facebookUrl: "https://www.facebook.com/addictivepain/",
    instagramUrl: "https://www.instagram.com/marisakmillingtontattoos",
  },
  {
    slug: "brian-langer",
    name: "Brian Langer",
    role: "Artist",
    bio: "Add a short bio for Brian Langer here—style, strengths, and what clients can expect.",
    avatarUrl: "/artists/placeholder.svg",
    specialties: ["black_and_grey", "traditional", "custom"],
    facebookUrl: "https://www.facebook.com/addictivepain/",
    instagramUrl: "https://www.instagram.com/",
  },
  {
    slug: "tom-bone",
    name: "Tom-Bone",
    role: "Piercer",
    bio: "Professional piercing with a focus on cleanliness, comfort, and proper jewelry selection.",
    avatarUrl: "/artists/tom-bone.jpg",
    specialties: ["custom"],
    facebookUrl: "https://www.facebook.com/addictivepain/",
    instagramUrl: "https://www.instagram.com/",
  },
  {
    slug: "ron-holt",
    name: "Ron Holt",
    role: "Tattoo Laser Removal Specialist",
    bio: "Professional tattoo laser removal services using advanced laser technology. Expert in safe, effective removal of unwanted tattoos with minimal discomfort and optimal results.",
    avatarUrl: "/artists/ron-holt.jpg",
    specialties: ["laser_removal"],
    facebookUrl: "https://www.facebook.com/addictivepain/",
    instagramUrl: "https://www.instagram.com/",
  },
  {
    slug: "gavin-gomula",
    name: "Gavin Gomula",
    role: "Apprentice",
    bio: "Learning the craft and developing skills in various tattoo styles. Working under experienced artists to master technique and build a strong foundation.",
    avatarUrl: "/artists/placeholder.svg",
    specialties: ["custom", "black_and_grey"],
    facebookUrl: "https://www.facebook.com/addictivepain/",
    instagramUrl: "https://www.instagram.com/",
  },
];
