import type { Tattoo } from "@/lib/types";

export const tattoos: Tattoo[] = [
  {
    id: "t2",
    artistSlug: "big-russ",
    title: "Realism sleeve - Lighthouse & Clock",
    imageUrl: "/tattoos/modern-1.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t3",
    artistSlug: "big-russ",
    title: "American Traditional portrait",
    imageUrl: "/tattoos/traditional-1.png",
    styles: ["traditional", "color"],
  },
  {
    id: "t4",
    artistSlug: "big-russ",
    title: "Realism angel",
    imageUrl: "/tattoos/modern-2.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t5",
    artistSlug: "big-russ",
    title: "Black & Grey Realism",
    imageUrl: "/tattoos/russ-3774.png",
    styles: ["black_and_grey", "realism"],
  },
  {
    id: "t9",
    artistSlug: "big-russ",
    title: "Horror Theme Work",
    imageUrl: "/tattoos/russ-3840.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "t10",
    artistSlug: "big-russ",
    title: "Realism Portrait Work",
    imageUrl: "/tattoos/russ-3842.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t11",
    artistSlug: "big-russ",
    title: "Custom Black & Grey Design",
    imageUrl: "/tattoos/russ-3843.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "t12",
    artistSlug: "big-russ",
    title: "Realism Sleeve Work",
    imageUrl: "/tattoos/russ-3844.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t13",
    artistSlug: "big-russ",
    title: "Detailed Portrait",
    imageUrl: "/tattoos/russ-3845.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t14",
    artistSlug: "big-russ",
    title: "Custom Black & Grey Piece",
    imageUrl: "/tattoos/russ-3846.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "t15",
    artistSlug: "big-russ",
    title: "Realism Work in Progress",
    imageUrl: "/tattoos/russ-3847.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t16",
    artistSlug: "big-russ",
    title: "Horror Theme Portrait",
    imageUrl: "/tattoos/russ-3848.png",
    styles: ["realism", "black_and_grey", "custom"],
  },
  {
    id: "t17",
    artistSlug: "big-russ",
    title: "Ghostface Stencil Work",
    imageUrl: "/tattoos/russ-3855.png",
    styles: ["custom", "black_and_grey"],
  },
  {
    id: "t18",
    artistSlug: "big-russ",
    title: "Realism Portrait Detail",
    imageUrl: "/tattoos/russ-3856.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t19",
    artistSlug: "big-russ",
    title: "Custom Black & Grey Design",
    imageUrl: "/tattoos/russ-3860.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "kenny-1",
    artistSlug: "kenny-briggs",
    title: "Leopard with Floral Elements",
    imageUrl: "/tattoos/kenny-leopard-floral.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kenny-2",
    artistSlug: "kenny-briggs",
    title: "Cinderella with Bubbles",
    imageUrl: "/tattoos/kenny-cinderella-bubbles.png",
    styles: ["color", "custom", "anime"],
  },
  {
    id: "kenny-3",
    artistSlug: "kenny-briggs",
    title: "Sea Turtle with Flowers",
    imageUrl: "/tattoos/kenny-sea-turtle-floral.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kenny-4",
    artistSlug: "kenny-briggs",
    title: "Clouds and Butterflies",
    imageUrl: "/tattoos/kenny-clouds-butterflies.png",
    styles: ["color", "custom"],
  },
  {
    id: "kenny-5",
    artistSlug: "kenny-briggs",
    title: "Peonies Thigh Piece",
    imageUrl: "/tattoos/kenny-peonies-thigh.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kenny-6",
    artistSlug: "kenny-briggs",
    title: "Evil Queen with Poisoned Apple",
    imageUrl: "/tattoos/kenny-evil-queen-apple.png",
    styles: ["color", "custom", "anime"],
  },
  {
    id: "kenny-7",
    artistSlug: "kenny-briggs",
    title: "Moth with Skull Head",
    imageUrl: "/tattoos/kenny-moth-skull.png",
    styles: ["black_and_grey", "neo_traditional", "custom"],
  },
  {
    id: "kenny-8",
    artistSlug: "kenny-briggs",
    title: "Cute Sea Turtles",
    imageUrl: "/tattoos/kenny-sea-turtles-cute.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kenny-9",
    artistSlug: "kenny-briggs",
    title: "Rooster with Sailor Hat",
    imageUrl: "/tattoos/kenny-rooster-sailor.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kenny-10",
    artistSlug: "kenny-briggs",
    title: "Shark-Insect Hybrid",
    imageUrl: "/tattoos/kenny-shark-insect.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "kenny-11",
    artistSlug: "kenny-briggs",
    title: "Black Cat with Flowers",
    imageUrl: "/tattoos/kenny-cat-flowers.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kenny-12",
    artistSlug: "kenny-briggs",
    title: "Macrame Plant Hanger",
    imageUrl: "/tattoos/kenny-macrame-plant.png",
    styles: ["color", "custom"],
  },
  {
    id: "kenny-13",
    artistSlug: "kenny-briggs",
    title: "Dragonfly with Love Mom",
    imageUrl: "/tattoos/kenny-dragonfly-love-mom.png",
    styles: ["black_and_grey", "fine_line", "custom"],
  },
  {
    id: "kenny-14",
    artistSlug: "kenny-briggs",
    title: "Power Ranger Helmet",
    imageUrl: "/tattoos/kenny-power-ranger.png",
    styles: ["color", "custom", "anime"],
  },
  {
    id: "kenny-15",
    artistSlug: "kenny-briggs",
    title: "Ship's Steering Wheel",
    imageUrl: "/tattoos/kenny-ship-wheel.png",
    styles: ["black_and_grey", "traditional", "custom"],
  },
  {
    id: "kenny-16",
    artistSlug: "kenny-briggs",
    title: "Hannya Mask",
    imageUrl: "/tattoos/kenny-hannya-mask.png",
    styles: ["color", "traditional", "custom"],
  },
  {
    id: "kenny-17",
    artistSlug: "kenny-briggs",
    title: "Brand of Sacrifice - Berserk",
    imageUrl: "/tattoos/kenny-brand-of-sacrifice.png",
    styles: ["custom", "realism", "anime"],
  },
  {
    id: "kenny-18",
    artistSlug: "kenny-briggs",
    title: "Angelic Portrait with Wings and Cross",
    imageUrl: "/tattoos/kenny-angel-portrait.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kenny-19",
    artistSlug: "kenny-briggs",
    title: "Bull Skull with Sunflower",
    imageUrl: "/tattoos/kenny-bull-skull-sunflower.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kenny-20",
    artistSlug: "kenny-briggs",
    title: "Black Cat with Flowers",
    imageUrl: "/tattoos/kenny-cat-flowers-2.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kenny-21",
    artistSlug: "kenny-briggs",
    title: "Ship's Steering Wheel",
    imageUrl: "/tattoos/kenny-ship-wheel.png",
    styles: ["black_and_grey", "traditional", "custom"],
  },
  {
    id: "kenny-22",
    artistSlug: "kenny-briggs",
    title: "Panther with Yellow Flower and Red Rose",
    imageUrl: "/tattoos/kenny-panther-rose.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "t24",
    artistSlug: "big-russ",
    title: "Macabre Portrait with Decayed Face",
    imageUrl: "/tattoos/russ-macabre-portrait.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "t26",
    artistSlug: "big-russ",
    title: "Black & Grey Realism Warrior Portrait",
    imageUrl: "/tattoos/russ-warrior-portrait.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "t27",
    artistSlug: "big-russ",
    title: "Freddy Krueger & Jason Voorhees Horror Portrait",
    imageUrl: "/tattoos/russ-freddy-jason.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "t28",
    artistSlug: "big-russ",
    title: "Horror Sleeve - Michael Myers, Jack-O-Lantern & Chucky",
    imageUrl: "/tattoos/russ-horror-sleeve.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "t29",
    artistSlug: "big-russ",
    title: "Horror Portrait Sleeve - Pennywise, Billy & Chucky",
    imageUrl: "/tattoos/russ-pennywise-chucky.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "t30",
    artistSlug: "big-russ",
    title: "Artist at Work - Tattooing Process",
    imageUrl: "/tattoos/russ-working.png",
    styles: ["custom"],
  },
  {
    id: "ron-1",
    artistSlug: "ron-holt",
    title: "Laser Removal Session - Leg Tattoo",
    imageUrl: "/tattoos/ron-laser-removal-1.png",
    styles: ["laser_removal", "before_after"],
  },
  {
    id: "ron-2",
    artistSlug: "ron-holt",
    title: "Laser Removal Procedure in Progress",
    imageUrl: "/tattoos/ron-laser-removal-2.png",
    styles: ["laser_removal", "before_after"],
  },
  {
    id: "ron-3",
    artistSlug: "ron-holt",
    title: "Professional Laser Removal Treatment",
    imageUrl: "/tattoos/ron-laser-removal-3.png",
    styles: ["laser_removal", "before_after"],
  },
  {
    id: "ron-4",
    artistSlug: "ron-holt",
    title: "Laser Removal Session - Upper Leg",
    imageUrl: "/tattoos/ron-laser-removal-4.png",
    styles: ["laser_removal", "before_after"],
  },
  {
    id: "kade-1",
    artistSlug: "kade-zapp",
    title: "Chest Piece - Sailing Ship & Tropical Beach",
    imageUrl: "/tattoos/kade-chest-ship-beach.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-2",
    artistSlug: "kade-zapp",
    title: "Praying Hands with Rose",
    imageUrl: "/tattoos/kade-praying-hands-rose.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-3",
    artistSlug: "kade-zapp",
    title: "Viking Longship Forearm",
    imageUrl: "/tattoos/kade-viking-ship.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-4",
    artistSlug: "kade-zapp",
    title: "Chest Tattoos - Maritime Theme",
    imageUrl: "/tattoos/kade-chest-tattoos.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-5",
    artistSlug: "kade-zapp",
    title: "Family Memorial - EST 2001",
    imageUrl: "/tattoos/kade-family-est2001.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-6",
    artistSlug: "kade-zapp",
    title: "Mandala & Floral Leg Piece",
    imageUrl: "/tattoos/kade-mandala-floral-leg.png",
    styles: ["fine_line", "black_and_grey", "floral", "custom"],
  },
  {
    id: "kade-7",
    artistSlug: "kade-zapp",
    title: "Gothic Nun Portrait",
    imageUrl: "/tattoos/kade-nun-portrait.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-8",
    artistSlug: "kade-zapp",
    title: "Brand of Sacrifice - Berserk",
    imageUrl: "/tattoos/kade-brand-of-sacrifice.png",
    styles: ["custom", "realism"],
  },
  {
    id: "kade-9",
    artistSlug: "kade-zapp",
    title: "Pocket Watch & Rose",
    imageUrl: "/tattoos/kade-pocket-watch-rose.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-10",
    artistSlug: "kade-zapp",
    title: "Skull Jellyfish",
    imageUrl: "/tattoos/kade-skull-jellyfish.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kade-11",
    artistSlug: "kade-zapp",
    title: "Lace Garter with Red Bow",
    imageUrl: "/tattoos/kade-lace-garter.png",
    styles: ["fine_line", "black_and_grey", "custom"],
  },
  {
    id: "kade-12",
    artistSlug: "kade-zapp",
    title: "Two Roses",
    imageUrl: "/tattoos/kade-two-roses.png",
    styles: ["black_and_grey", "realism", "floral", "custom"],
  },
  {
    id: "kade-13",
    artistSlug: "kade-zapp",
    title: "Pocket Watch & Rose Forearm",
    imageUrl: "/tattoos/kade-pocket-watch-rose-2.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-14",
    artistSlug: "kade-zapp",
    title: "Pennywise Portrait",
    imageUrl: "/tattoos/kade-pennywise.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-15",
    artistSlug: "kade-zapp",
    title: "Hannya Mask",
    imageUrl: "/tattoos/kade-hannya-mask.png",
    styles: ["black_and_grey", "traditional", "custom"],
  },
  {
    id: "marisa-01",
    artistSlug: "marissa-millington",
    title: "Black & Grey Realism Portrait",
    imageUrl: "/tattoos/marisa-01.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "marisa-02",
    artistSlug: "marissa-millington",
    title: "Fine Line Floral Design",
    imageUrl: "/tattoos/marisa-02.png",
    styles: ["fine_line", "floral", "custom"],
  },
  {
    id: "marisa-03",
    artistSlug: "marissa-millington",
    title: "Black & Grey Realism Piece",
    imageUrl: "/tattoos/marisa-03.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "marisa-04",
    artistSlug: "marissa-millington",
    title: "Dotwork Portrait Study",
    imageUrl: "/tattoos/marisa-04.png",
    styles: ["black_and_grey", "fine_line", "custom"],
  },
  {
    id: "marisa-05",
    artistSlug: "marissa-millington",
    title: "Realism Floral Arm Piece",
    imageUrl: "/tattoos/marisa-05.png",
    styles: ["black_and_grey", "realism", "floral"],
  },
  {
    id: "marisa-06",
    artistSlug: "marissa-millington",
    title: "Custom Black & Grey Design",
    imageUrl: "/tattoos/marisa-06.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "marisa-07",
    artistSlug: "marissa-millington",
    title: "Fine Line Realism Work",
    imageUrl: "/tattoos/marisa-07.png",
    styles: ["fine_line", "black_and_grey", "realism"],
  },
  {
    id: "marisa-08",
    artistSlug: "marissa-millington",
    title: "Stippled Portrait Art",
    imageUrl: "/tattoos/marisa-08.png",
    styles: ["black_and_grey", "fine_line", "custom"],
  },
  {
    id: "marisa-09",
    artistSlug: "marissa-millington",
    title: "Black & Grey Realism Sleeve",
    imageUrl: "/tattoos/marisa-09.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "marisa-10",
    artistSlug: "marissa-millington",
    title: "Custom Realism Portrait",
    imageUrl: "/tattoos/marisa-10.png",
    styles: ["realism", "black_and_grey", "custom"],
  },
  {
    id: "marisa-11",
    artistSlug: "marissa-millington",
    title: "Fine Line Floral Tattoo",
    imageUrl: "/tattoos/marisa-11.png",
    styles: ["fine_line", "floral", "custom"],
  },
  {
    id: "marisa-12",
    artistSlug: "marissa-millington",
    title: "Black & Grey Custom Design",
    imageUrl: "/tattoos/marisa-12.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "marisa-13",
    artistSlug: "marissa-millington",
    title: "Realism Portrait Work",
    imageUrl: "/tattoos/marisa-13.png",
    styles: ["realism", "black_and_grey", "custom"],
  },
  {
    id: "marisa-14",
    artistSlug: "marissa-millington",
    title: "Dotwork Fine Line Art",
    imageUrl: "/tattoos/marisa-14.png",
    styles: ["fine_line", "black_and_grey", "custom"],
  },
  {
    id: "marisa-15",
    artistSlug: "marissa-millington",
    title: "Black & Grey Realism Piece",
    imageUrl: "/tattoos/marisa-15.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "marisa-16",
    artistSlug: "marissa-millington",
    title: "Custom Floral Design",
    imageUrl: "/tattoos/marisa-16.png",
    styles: ["floral", "custom", "fine_line"],
  },
  {
    id: "marisa-17",
    artistSlug: "marissa-millington",
    title: "Realism Black & Grey Work",
    imageUrl: "/tattoos/marisa-17.png",
    styles: ["realism", "black_and_grey", "custom"],
  },
  {
    id: "marisa-18",
    artistSlug: "marissa-millington",
    title: "Fine Line Custom Tattoo",
    imageUrl: "/tattoos/marisa-18.png",
    styles: ["fine_line", "custom"],
  },
  {
    id: "marisa-19",
    artistSlug: "marissa-millington",
    title: "Black & Grey Portrait",
    imageUrl: "/tattoos/marisa-19.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "marisa-20",
    artistSlug: "marissa-millington",
    title: "Stippled Realism Portrait",
    imageUrl: "/tattoos/marisa-20.png",
    styles: ["black_and_grey", "fine_line", "realism"],
  },
  {
    id: "marisa-21",
    artistSlug: "marissa-millington",
    title: "Custom Black & Grey Design",
    imageUrl: "/tattoos/marisa-21.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "marisa-22",
    artistSlug: "marissa-millington",
    title: "Fine Line Realism Work",
    imageUrl: "/tattoos/marisa-22.png",
    styles: ["fine_line", "realism", "black_and_grey"],
  },
  {
    id: "marisa-23",
    artistSlug: "marissa-millington",
    title: "Black & Grey Custom Piece",
    imageUrl: "/tattoos/marisa-23.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "marisa-24",
    artistSlug: "marissa-millington",
    title: "Realism Floral Tattoo",
    imageUrl: "/tattoos/marisa-24.png",
    styles: ["realism", "floral", "black_and_grey"],
  },
  {
    id: "marisa-25",
    artistSlug: "marissa-millington",
    title: "Custom Fine Line Design",
    imageUrl: "/tattoos/marisa-25.png",
    styles: ["fine_line", "custom"],
  },
  {
    id: "marisa-26",
    artistSlug: "marissa-millington",
    title: "Black & Grey Realism Portrait",
    imageUrl: "/tattoos/marisa-26.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "marisa-27",
    artistSlug: "marissa-millington",
    title: "Fine Line Custom Work",
    imageUrl: "/tattoos/marisa-27.png",
    styles: ["fine_line", "custom"],
  },
  {
    id: "marisa-28",
    artistSlug: "marissa-millington",
    title: "Realism Black & Grey Design",
    imageUrl: "/tattoos/marisa-28.png",
    styles: ["realism", "black_and_grey", "custom"],
  },
  {
    id: "marisa-29",
    artistSlug: "marissa-millington",
    title: "Custom Portrait Tattoo",
    imageUrl: "/tattoos/marisa-29.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "marisa-30",
    artistSlug: "marissa-millington",
    title: "Black & Grey Fine Line Art",
    imageUrl: "/tattoos/marisa-30.png",
    styles: ["black_and_grey", "fine_line", "custom"],
  },
];
