import type { Tattoo } from "@/lib/types";

export const tattoos: Tattoo[] = [
  {
    id: "t2",
    artistSlug: "big-russ",
    title: "Realism sleeve - Lighthouse & Clock",
    imageUrl: "/tattoos/modern-1.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t3",
    artistSlug: "big-russ",
    title: "American Traditional portrait",
    imageUrl: "/tattoos/traditional-1.png",
    styles: ["traditional", "color"],
  },
  {
    id: "t4",
    artistSlug: "big-russ",
    title: "Realism angel",
    imageUrl: "/tattoos/modern-2.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t5",
    artistSlug: "big-russ",
    title: "Black & Grey Realism",
    imageUrl: "/tattoos/russ-3774.png",
    styles: ["black_and_grey", "realism"],
  },
  {
    id: "t9",
    artistSlug: "big-russ",
    title: "Horror Theme Work",
    imageUrl: "/tattoos/russ-3840.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "t10",
    artistSlug: "big-russ",
    title: "Realism Portrait Work",
    imageUrl: "/tattoos/russ-3842.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t11",
    artistSlug: "big-russ",
    title: "Custom Black & Grey Design",
    imageUrl: "/tattoos/russ-3843.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "t12",
    artistSlug: "big-russ",
    title: "Realism Sleeve Work",
    imageUrl: "/tattoos/russ-3844.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t13",
    artistSlug: "big-russ",
    title: "Detailed Portrait",
    imageUrl: "/tattoos/russ-3845.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t14",
    artistSlug: "big-russ",
    title: "Custom Black & Grey Piece",
    imageUrl: "/tattoos/russ-3846.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "t15",
    artistSlug: "big-russ",
    title: "Realism Work in Progress",
    imageUrl: "/tattoos/russ-3847.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t16",
    artistSlug: "big-russ",
    title: "Horror Theme Portrait",
    imageUrl: "/tattoos/russ-3848.png",
    styles: ["realism", "black_and_grey", "custom"],
  },
  {
    id: "t17",
    artistSlug: "big-russ",
    title: "Ghostface Stencil Work",
    imageUrl: "/tattoos/russ-3855.png",
    styles: ["custom", "black_and_grey"],
  },
  {
    id: "t18",
    artistSlug: "big-russ",
    title: "Realism Portrait Detail",
    imageUrl: "/tattoos/russ-3856.png",
    styles: ["realism", "black_and_grey"],
  },
  {
    id: "t19",
    artistSlug: "big-russ",
    title: "Custom Black & Grey Design",
    imageUrl: "/tattoos/russ-3860.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "kenny-1",
    artistSlug: "kenny-briggs",
    title: "Leopard with Floral Elements",
    imageUrl: "/tattoos/kenny-leopard-floral.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kenny-2",
    artistSlug: "kenny-briggs",
    title: "Cinderella with Bubbles",
    imageUrl: "/tattoos/kenny-cinderella-bubbles.png",
    styles: ["color", "custom", "anime"],
  },
  {
    id: "kenny-3",
    artistSlug: "kenny-briggs",
    title: "Sea Turtle with Flowers",
    imageUrl: "/tattoos/kenny-sea-turtle-floral.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kenny-4",
    artistSlug: "kenny-briggs",
    title: "Clouds and Butterflies",
    imageUrl: "/tattoos/kenny-clouds-butterflies.png",
    styles: ["color", "custom"],
  },
  {
    id: "kenny-5",
    artistSlug: "kenny-briggs",
    title: "Peonies Thigh Piece",
    imageUrl: "/tattoos/kenny-peonies-thigh.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kenny-6",
    artistSlug: "kenny-briggs",
    title: "Evil Queen with Poisoned Apple",
    imageUrl: "/tattoos/kenny-evil-queen-apple.png",
    styles: ["color", "custom", "anime"],
  },
  {
    id: "kenny-7",
    artistSlug: "kenny-briggs",
    title: "Moth with Skull Head",
    imageUrl: "/tattoos/kenny-moth-skull.png",
    styles: ["black_and_grey", "neo_traditional", "custom"],
  },
  {
    id: "kenny-8",
    artistSlug: "kenny-briggs",
    title: "Cute Sea Turtles",
    imageUrl: "/tattoos/kenny-sea-turtles-cute.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kenny-9",
    artistSlug: "kenny-briggs",
    title: "Rooster with Sailor Hat",
    imageUrl: "/tattoos/kenny-rooster-sailor.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kenny-10",
    artistSlug: "kenny-briggs",
    title: "Shark-Insect Hybrid",
    imageUrl: "/tattoos/kenny-shark-insect.png",
    styles: ["black_and_grey", "custom"],
  },
  {
    id: "kenny-11",
    artistSlug: "kenny-briggs",
    title: "Black Cat with Flowers",
    imageUrl: "/tattoos/kenny-cat-flowers.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kenny-12",
    artistSlug: "kenny-briggs",
    title: "Macrame Plant Hanger",
    imageUrl: "/tattoos/kenny-macrame-plant.png",
    styles: ["color", "custom"],
  },
  {
    id: "kenny-13",
    artistSlug: "kenny-briggs",
    title: "Dragonfly with Love Mom",
    imageUrl: "/tattoos/kenny-dragonfly-love-mom.png",
    styles: ["black_and_grey", "fine_line", "custom"],
  },
  {
    id: "kenny-14",
    artistSlug: "kenny-briggs",
    title: "Power Ranger Helmet",
    imageUrl: "/tattoos/kenny-power-ranger.png",
    styles: ["color", "custom", "anime"],
  },
  {
    id: "kenny-15",
    artistSlug: "kenny-briggs",
    title: "Ship's Steering Wheel",
    imageUrl: "/tattoos/kenny-ship-wheel.png",
    styles: ["black_and_grey", "traditional", "custom"],
  },
  {
    id: "kenny-16",
    artistSlug: "kenny-briggs",
    title: "Hannya Mask",
    imageUrl: "/tattoos/kenny-hannya-mask.png",
    styles: ["color", "traditional", "custom"],
  },
  {
    id: "t24",
    artistSlug: "big-russ",
    title: "Macabre Portrait with Decayed Face",
    imageUrl: "/tattoos/russ-macabre-portrait.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "ron-1",
    artistSlug: "ron-holt",
    title: "Laser Removal Session - Leg Tattoo",
    imageUrl: "/tattoos/ron-laser-removal-1.png",
    styles: ["laser_removal", "before_after"],
  },
  {
    id: "ron-2",
    artistSlug: "ron-holt",
    title: "Laser Removal Procedure in Progress",
    imageUrl: "/tattoos/ron-laser-removal-2.png",
    styles: ["laser_removal", "before_after"],
  },
  {
    id: "ron-3",
    artistSlug: "ron-holt",
    title: "Professional Laser Removal Treatment",
    imageUrl: "/tattoos/ron-laser-removal-3.png",
    styles: ["laser_removal", "before_after"],
  },
  {
    id: "ron-4",
    artistSlug: "ron-holt",
    title: "Laser Removal Session - Upper Leg",
    imageUrl: "/tattoos/ron-laser-removal-4.png",
    styles: ["laser_removal", "before_after"],
  },
  {
    id: "kade-1",
    artistSlug: "kade-zapp",
    title: "Chest Piece - Sailing Ship & Tropical Beach",
    imageUrl: "/tattoos/kade-chest-ship-beach.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-2",
    artistSlug: "kade-zapp",
    title: "Praying Hands with Rose",
    imageUrl: "/tattoos/kade-praying-hands-rose.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-3",
    artistSlug: "kade-zapp",
    title: "Viking Longship Forearm",
    imageUrl: "/tattoos/kade-viking-ship.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-4",
    artistSlug: "kade-zapp",
    title: "Chest Tattoos - Maritime Theme",
    imageUrl: "/tattoos/kade-chest-tattoos.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-5",
    artistSlug: "kade-zapp",
    title: "Family Memorial - EST 2001",
    imageUrl: "/tattoos/kade-family-est2001.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-6",
    artistSlug: "kade-zapp",
    title: "Mandala & Floral Leg Piece",
    imageUrl: "/tattoos/kade-mandala-floral-leg.png",
    styles: ["fine_line", "black_and_grey", "floral", "custom"],
  },
  {
    id: "kade-7",
    artistSlug: "kade-zapp",
    title: "Gothic Nun Portrait",
    imageUrl: "/tattoos/kade-nun-portrait.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-8",
    artistSlug: "kade-zapp",
    title: "Brand of Sacrifice - Berserk",
    imageUrl: "/tattoos/kade-brand-of-sacrifice.png",
    styles: ["custom", "realism"],
  },
  {
    id: "kade-9",
    artistSlug: "kade-zapp",
    title: "Pocket Watch & Rose",
    imageUrl: "/tattoos/kade-pocket-watch-rose.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-10",
    artistSlug: "kade-zapp",
    title: "Skull Jellyfish",
    imageUrl: "/tattoos/kade-skull-jellyfish.png",
    styles: ["color", "neo_traditional", "custom"],
  },
  {
    id: "kade-11",
    artistSlug: "kade-zapp",
    title: "Lace Garter with Red Bow",
    imageUrl: "/tattoos/kade-lace-garter.png",
    styles: ["fine_line", "black_and_grey", "custom"],
  },
  {
    id: "kade-12",
    artistSlug: "kade-zapp",
    title: "Two Roses",
    imageUrl: "/tattoos/kade-two-roses.png",
    styles: ["black_and_grey", "realism", "floral", "custom"],
  },
  {
    id: "kade-13",
    artistSlug: "kade-zapp",
    title: "Pocket Watch & Rose Forearm",
    imageUrl: "/tattoos/kade-pocket-watch-rose-2.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-14",
    artistSlug: "kade-zapp",
    title: "Pennywise Portrait",
    imageUrl: "/tattoos/kade-pennywise.png",
    styles: ["black_and_grey", "realism", "custom"],
  },
  {
    id: "kade-15",
    artistSlug: "kade-zapp",
    title: "Hannya Mask",
    imageUrl: "/tattoos/kade-hannya-mask.png",
    styles: ["black_and_grey", "traditional", "custom"],
  },
];
